### ISSUE TITLE
Hello, I cannot find the ERE datasets in LDC

### ISSUE THREAD

**Issue by RZFan525** [PlusLabNLP/X-Gear#1]
Hello, I cannot find the ERE datasets in LDC. 
<img width="732" alt="image" src="https://user-images.githubusercontent.com/41265224/160566290-db672dde-2e9d-4032-887d-ed38e28be935.png">
Could you give me some details? 
Thank you!
Best wishes!

**Comment by ihungalexhsu** [comment]
Hi, sorry these datasets are not free, you need to get access to LDC catalog to access them. We're not in the position to share them privately, but many schools have the license. You can probably contact your librarian or your advisor to get access.
