### ISSUE TITLE
the classification f1 about en to ar

### ISSUE THREAD

**Issue by mahuipeng98** [PlusLabNLP/X-Gear#3]
In your paper(Multilingual Generative Language Models for Zero-Shot Cross-Lingual Event Argument Extraction), the classification f1 about en to ar is 44.8(mT5-large). But in github readme.md, the classification f1 about en to ar is 50.00(mT5-large). Why?

**Comment by ihungalexhsu** [comment]
Hi, I think this is because the paper's result is the average score across many random seeds. The model we put is the best model we have.

**Comment by mahuipeng98** [comment]
> 

Thank you for your reply. Best wishes.
