### ISSUE TITLE
dataset share

### ISSUE THREAD

**Issue by qlzw0530** [PlusLabNLP/X-Gear#4]
I am very happy to read your published paper. Could you please share the processed ACE2005 dataset.
My lab has access to the ACE2005 dataset, but there are always problems during the data processing phase.
Thanks for sharing.

**Comment by ihungalexhsu** [comment]
Could you please post the issues here? So the other follow-ups can also reference.

**Comment by qlzw0530** [comment]
> Could you please post the issues here? So the other follow-ups can also reference.

i wanted your processed ACE2005 dataset

**Comment by ihungalexhsu** [comment]
These datasets are not free, so we cannot share processed data with you. You need to get access to the LDC catalog to access them. We're not in the position to share them privately, but many schools have the license. You can probably contact your librarian or your advisor to get access.

If you have accessed the data and cannot run our processing code, please share the error here.

**Comment by qlzw0530** [comment]
> These datasets are not free, so we cannot share processed data with you. You need to get access to the LDC catalog to access them. We're not in the position to share them privately, but many schools have the license. You can probably contact your librarian or your advisor to get access.
> 
> If you have accessed the data and cannot run our processing code, please share the error here.

Yes, our laboratory has permission, but in order to process the experimental data more consistently, we took the liberty to ask you for it. I hope you don't mind.

**Comment by ihungalexhsu** [comment]
If you use the same environment and run our scripts, I think the data will be the same. Again, sorry that we cannot share because we need to follow the license of the data.

**Comment by qlzw0530** [comment]
> If you use the same environment and run our scripts, I think the data will be the same. Again, sorry that we cannot share because we need to follow the license of the data.

Ok, thanks, I'll deal with it as you said.
