### ISSUE TITLE
the format of the processed chinese dataset

### ISSUE THREAD

**Issue by awhathell** [PlusLabNLP/X-Gear#5]
Hello, I would like to run the code on a custom chinese dataset. Can you share the format of the processed chinese dataset? So that I can change the format of my dataset to a format that the program can run

**Comment by ihungalexhsu** [comment]
Hi, 
Thanks for your interest in our work. The format that our model support can be viewed in https://github.com/PlusLabNLP/X-Gear/blob/main/processed_data/ace05_ar_mT5/dev.json
You may need to look at the fields we have in this json file.
