### ISSUE TITLE
您好！我使用ACE05中文数据集进行训练时，Role I与Role C的PRF结果均为0，不太清楚哪里出问题了。烦请解答。

### ISSUE THREAD

**Issue by GaoYang-debug** [PlusLabNLP/X-Gear#6]
您好！我使用ACE05中文数据集进行训练时，Role I与Role C的PRF结果均为0，不太清楚哪里出问题了。烦请解答。
![1](https://github.com/PlusLabNLP/X-Gear/assets/72145849/de544e28-91bb-46f3-9313-ac50b7dea495)
![2](https://github.com/PlusLabNLP/X-Gear/assets/72145849/8bfb3617-dd6e-4ccd-8a64-4130c1166be8)

**Comment by ej0cl6** [comment]
Hi, If you choose mT5 as the base model, it's normal to get zero scores for the first few epochs with the default configuration . Usually after 10 epochs, you will see non-zero scores.

**Comment by GaoYang-debug** [comment]
OK，非常感谢你的回复！
